apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
  namespace: bankapp-namespace
spec:
  selector:
    app: bankapp-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
